### ISSUE TITLE
【求助】发现一个问题，我没有找到解决办法，

### ISSUE THREAD

**Issue by hyoutom** [dulaiduwang003/TIME-SEA-chatgpt#26]
当vue页面发送消息，websocket 消息体过大，比如超过2万字，后端会拒绝socket消息，前端直接断开，并没有任何响应。我不知道该在那里配置这个请求大小限制和websocket超时时间

**Comment by dulaiduwang003** [comment]
建议用 新版本 ts-gpt仓库 ,这个问题以解决
